---
categories:
  feature: 'ğŸš€ Features:'
  bug: 'ğŸ› Bug fixes:'
  technical: 'ğŸ”§ Technical enhancements:'
  breaking: 'âš¡ Breaking changes:'
  dependencies: 'ğŸ‘’ Dependencies:'
  doc: 'ğŸ“– Documentation:'
  release: 'ğŸ”¹ Release:'
